---

#
### WEB SERVICE TESTS
#

- name: Test if web service is up and running
  shell: >
    curl -k -I "http://localhost:8000"
    | grep "HTTP/1.1 200 OK"
  changed_when: False

# vim: set ts=8 sts=2 sw=2 et:
