---

#
### WEB SERVICE ###
#
# Simple web service deployment with underlying database creation and load
# balancer join.
#

- name: Install packages
  apt:
    pkg: "{{ item }}"
    force: yes
    install_recommends: no
    state: latest
  with_items:
    - gunicorn
    - python-psycopg2
  environment: "{{ proxy_env }}"
  become: yes


### DATABASE CREATION
- name: Create database
  postgresql_db:
    name: dbstats
    encoding: 'UTF-8'
    template: template_postgis
    state: present
  become: yes
  become_user: postgres
  delegate_to: db

- name: Create database user
  postgresql_user:
    name: "{{ WEB_USER_NAME }}"
    password: "{{ WEB_USER_PASSWORD }}"
    state: present
  become: yes
  become_user: postgres
  delegate_to: db

- name: Grant database user privileges
  postgresql_privs:
    db: dbstats
    type: group
    objs: dbusers
    roles: dbstats
    state: present
  become: yes
  become_user: postgres
  delegate_to: db


### DEPLOYMENT
- name: Install db-stats script
  copy:
    src: static/db-stats/db-stats.py
    dest: /opt/db-stats.py
  become: yes

- name: Install db-stats service
  template:
    src: init/rc.local.j2
    dest: /etc/rc.local
  become: yes

- name: Start db-stats service
  command: /etc/rc.local
  become: yes


### LOAD BALANCER JOIN
- name: Add web service to load balancer
  shell: >
    sed -i "/# worker-{{ HOST_NUMBER }}/d" /etc/haproxy/haproxy.cfg
    &&
    echo "server {{ ansible_hostname }}_{{ HOST_NUMBER }} 172.20.20.{{ HOST_NUMBER }}:8000 check observe layer7  # worker-{{ HOST_NUMBER }}"
    >> /etc/haproxy/haproxy.cfg
    &&
    service haproxy reload
  become: yes
  delegate_to: lb

# vim: set ts=8 sts=2 sw=2 et:
