---

#
### DATABASE SERVICE TESTS ###
#

- name: Test if database is up and running
  shell: >
    psql -U postgres -d postgres -tAc "SELECT version()"
  become: yes
  ignore_errors: yes
  changed_when: False

# vim: set ts=8 sts=2 sw=2 et:
